config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users

  get 'dashboard', to: 'dashboard#index', as: :user_root

  scope 'admin' do
    get 'game/index'
    post 'game/start'
    post 'game/stop'

    resources :teams do
      get 'logs', on: :member
      get 'deploy', on: :member
    end
  end

  resource :myteam, controller: :my_team do
    post 'join', on: :member
    post 'leave', on: :member
  end

  get 'stats/overall'
  get 'stats/overall_charts'
  get 'stats/rounds'
  get 'stats/simulator'
  get 'stats/elevator_states'
  get 'stats/floor_states'

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_team

  def index; end

  private

  def set_team
    @team = current_user.team
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_decider_app.html.slim
dl.dl-horizontal
  dt App
  dd = link_to @team.decider_app.name, @team.decider_app.web_url
  dt Original Repository
  dd = link_to @team.extended_git_url, @team.extended_git_url
  dt Your App-Logs
  dd = link_to logs_team_path(@team), logs_team_path(@team)
  dt Last Deployment
  dd = @team.last_deployment ? (link_to 'Deployment Log', @team.last_deployment, target: '_blank') : 'Never'

= link_to 'Deploy', deploy_team_path(@team), class: 'btn btn-primary'

app/views/dashboard/_team.html.slim
div.panel.panel-default
  .panel-heading.clearfix
    i.fa.fa-2x.fa-users
    '
    | &nbsp;
    strong = team.name
    '
    | (#{pluralize(team.users.count, 'member')})
  .panel-body
    = link_to 'Join Team', join_myteam_path(id: team.id), method: :post, class: 'btn btn-default pull-right'
    - if team.users
      p Members:
      ul
        - team.users.each do |u|
          li = u.email

app/views/dashboard/_user.html.slim
- digest = Digest::MD5.hexdigest(user.email.downcase.strip)
img.img-circle src="https://www.gravatar.com/avatar/#{digest}" alt=user.email title=user.email
'
|

app/views/dashboard/index.html.slim
h1 Dashboard

- if @team
  h2 Team #{@team.name}
  .panel.panel-default
    .panel-heading Team Members
    .panel-body
      = render partial: 'user', collection: @team.users
      .clearfix
        = link_to 'I want to leave.', leave_myteam_path, method: :post, class: 'btn btn-danger pull-right', data: {confirm: 'Are you sure?'}

  - if @team.decider_app
    .panel.panel-default
      .panel-heading Decider App
      .panel-body = render partial: 'decider_app'

    = render partial: 'shared/live_stats'
  - else
    .alert.alert-danger You have no decider app configured.

- else
  h2 Available Teams
  = render partial: 'team', collection: Team.all
  .panel.panel-primary
    .panel-heading Build a new team
    .panel-body
      p You can also create your own team.
      = link_to 'Create new team now', new_myteam_path, class: 'btn btn-primary'