config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users

  get 'dashboard', to: 'dashboard#index', as: :user_root

  scope 'admin' do
    get 'game/index'
    post 'game/start'
    post 'game/stop'

    resources :teams do
      get 'logs', on: :member
      get 'deploy', on: :member
    end
  end

  resource :myteam, controller: :my_team do
    post 'join', on: :member
    post 'leave', on: :member
  end

  get 'stats/overall'
  get 'stats/overall_charts'
  get 'stats/rounds'
  get 'stats/simulator'
  get 'stats/elevator_states'
  get 'stats/floor_states'

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    @rounds_played = Round.count
    @game_config = game_config
  end

  def start
    Redis.current.set('game_state', 'running')
    game_config = setup_option_params.to_hash.symbolize_keys
    store_game_config_to_session(game_config)
    GameJob.perform_later(game_config)
    redirect_to game_index_path
  end

  def stop
    Redis.current.set('game_state', 'stopped')
    redirect_to game_index_path
  end

  def setup_option_params
    params.require(:start_with_game_config).permit(:building_size, :decider_timeout, :round_delay, :round_limit)
  end

  private

  def game_config
    return session[:game_config].symbolize_keys if session[:game_config]
    PlayMasterService.default_setup_options
  end

  def store_game_config_to_session(game_config)
    session[:game_config] = game_config
  end
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/index.html.slim
h1 Play Master View

.panel.panel-default
  .panel-heading All Registered Apps
  .panel-body
    ul
      - DeciderApp.all.each do |app|
        li #{link_to(app.name, app.web_url)} by team <i>#{link_to(app.team.name, team_path(app.team))}</i>

ul.list-inline
  li = link_to 'Stop', game_stop_path, method: :post, class: 'btn btn-primary'

.panel.panel-default
  .panel-heading Starting a game
  .panel-body
    = simple_form_for :start_with_game_config, url: game_start_url do |f|
      .form-inputs
        .form-group
          .input-group
            = f.input :building_size, as: :integer, input_html: { value: @game_config[:building_size] }
        .form-group
          .input-group
            = f.input :decider_timeout, as: :decimal, input_html: { value: @game_config[:decider_timeout] }
        .form-group
          .input-group
            = f.input :round_delay, as: :integer, input_html: { value: @game_config[:round_delay] }
        .form-group
          .input-group
            = f.input :round_limit, as: :integer, input_html: { value: @game_config[:round_limit] }
      .form-actions
        = f.button :submit, class: 'btn btn-primary', value: 'Start'

= render partial: 'shared/live_stats'