config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users

  get 'dashboard', to: 'dashboard#index', as: :user_root

  scope 'admin' do
    get 'game/index'
    post 'game/start'
    post 'game/stop'

    resources :teams do
      get 'logs', on: :member
      get 'deploy', on: :member
    end
  end

  resource :myteam, controller: :my_team do
    post 'join', on: :member
    post 'leave', on: :member
  end

  get 'stats/overall'
  get 'stats/overall_charts'
  get 'stats/rounds'
  get 'stats/simulator'
  get 'stats/elevator_states'
  get 'stats/floor_states'

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/stats_controller.rb
require 'csv'

class StatsController < ApplicationController
  def overall_charts
    # TODO: Show teams in graph, and what about autoupdate?
    team_names = Team.all.order(:id).pluck(:name)
    graph_data = []


    building_states = BuildingState.where('id % 10 = 0').last(100)

    building_states.each do |state|
      state.elevators.each_with_index do |_elevator, i|
        graph_data[i] = { name: team_names[i], data: [] }
      end
    end

    building_states.each do |state|
      state.elevators.each_with_index do |elevator, i|
        graph_data[i][:data].push([state.round_id, elevator.people_transported])
      end
    end

    render json: graph_data.chart_json
  end

  def rounds
    @round_count = Round.count
  end

  def simulator
    @round_id = params[:round_id] ? params[:round_id].to_i : Round.minimum(:id)
    return unless Round.exists?(@round_id)

    round = Round.find(@round_id)
    floors = round.building_state.floors
    elevators = round.building_state.elevators

    @output = floors.map.with_index do |floor, level|
      floor_label = level.to_s.rjust(3)

      chamber = elevators.map do |elevator|
        if level == elevator.floor_number
          "[#{elevator.people_carrying}]"
        else
          '   '
        end
      end.join(' | ')

      waiting_people = '웃' * floor.people_waiting

      "#{floor_label} █ #{chamber} █ #{waiting_people}"
    end.reverse.join("\n")
  end

  def floor_states
    respond_to do |format|
      format.csv do
        set_csv_headers('floors_per_round.csv')
        self.response_body = floor_states_csv_lines(age_param.ago)
      end
    end
  end

  def elevator_states
    respond_to do |format|
      format.csv do
        set_csv_headers('elevators_per_round.csv')
        self.response_body = elevator_states_csv_lines(age_param.ago)
      end
    end
  end

  def set_csv_headers(filename)
    headers["X-Accel-Buffering"] = "no"
    headers["Cache-Control"] = "no-cache"
    headers["Content-Type"] = "text/csv; charset=utf-8"
    headers["Content-Disposition"] = %(attachment; filename="#{filename}")
    headers["Last-Modified"] = Time.zone.now.ctime.to_s
  end

  private

  def age_param
    (params[:age].to_i || 5).minutes
  end

  def floor_states_csv_lines(start_at)
    Enumerator.new do |y|
      y << CSV.generate_line(['Round ID', 'Floor Number', 'People Waiting'])

      Round.joins(:building_state).includes(:building_state)
          .where('rounds.created_at > ?', start_at).find_each.lazy.each do |round|
        round.building_state.floors.map.with_index do |floor, i|
          y << CSV.generate_line([round.id, i, floor.people_waiting])
        end
      end
    end
  end

  def elevator_states_csv_lines(start_at)
    Enumerator.new do |y|
      y << CSV.generate_line(['Round ID', 'Elevator Number', 'Current Floor', 'People Carrying', 'Total Transported'])

      Round.joins(:building_state).includes(:building_state)
          .where('rounds.created_at > ?', start_at).find_each.lazy.each do |round|
        round.building_state.elevators.each_with_index do |elevator, i|
          y << CSV.generate_line([round.id, i, elevator.floor_number, elevator.people_carrying, elevator.people_transported])
        end
      end
    end
  end
end

app/views/stats/overall.html.slim
- content_for :head do
  = javascript_include_tag "//www.google.com/jsapi", "chartkick"


h1 Lean Elevator Challenge

h2 Statistics

h3 Total Transports per Team
= line_chart stats_overall_charts_path

h3 Floor States


h3 Elevator States

app/views/stats/rounds.html.slim
h1 Lean Elevator Challenge

h2 Detailed Round Statistics

- if @round_count > 0
  .row
    .col-md-12
      .panel.panel-default
        .panel-heading Meta
        .panel-body
          dl.dl-horizontal
            dt Rounds played
            dd = @round_count

  .row
    .col-md-6
      .panel.panel-default
        .panel-heading Floor State CSV
        .panel-body
          i This download may take long
          = form_tag(stats_floor_states_path(format: :csv), method: 'get')
            .form-group
              = label_tag(:age, 'Age in minutes:')
              = number_field_tag(:age, 5, class: 'form-control', placeholder: '5')
            = submit_tag('Download Floor States', class: 'btn btn-primary')


    .col-md-6
      .panel.panel-default
        .panel-heading Elevator State CSV
        .panel-body
          i This download may take long
          = form_tag(stats_elevator_states_path(format: :csv), method: 'get')
            .form-group
              = label_tag(:age, 'Age in minutes:')
              = number_field_tag(:age, 5, class: 'form-control', placeholder: '5')
            = submit_tag('Download Elevator States', class: 'btn btn-primary')

- else
  p No rounds played yet.

app/views/stats/simulator.html.slim
h1 Lean Elevator Challenge

- if Round.any?
  h2 Round #{@round_id}

  pre#simulator[data-round=@round_id data-round-max=Round.maximum(:id)] = @output

  ul.list-inline
    li
      - if @round_id > Round.minimum(:id)
        = link_to stats_simulator_path(round_id: @round_id - 1), class: 'btn btn-primary' do
          i.fa.fa-step-backward
          = ' Show Previous'
        end
    li
      - if @round_id < Round.maximum(:id)
        = link_to stats_simulator_path(round_id: @round_id + 1), class: 'btn btn-primary' do
          i.fa.fa-step-forward
          = ' Show Next'
        end
        end


- else
  p Simulator is not available until the game started.