config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users

  get 'dashboard', to: 'dashboard#index', as: :user_root

  scope 'admin' do
    get 'game/index'
    post 'game/start'
    post 'game/stop'

    resources :teams do
      get 'logs', on: :member
      get 'deploy', on: :member
    end
  end

  resource :myteam, controller: :my_team do
    post 'join', on: :member
    post 'leave', on: :member
  end

  get 'stats/overall'
  get 'stats/overall_charts'
  get 'stats/rounds'
  get 'stats/simulator'
  get 'stats/elevator_states'
  get 'stats/floor_states'

  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-default role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle data-target="#application-navbar" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to '↕[웃]', user_root_path, class: 'navbar-brand'

    #application-navbar.collapse.navbar-collapse
      ul.nav.navbar-nav
        li = link_to 'Dashboard', user_root_path
        li = link_to 'Simulator', stats_simulator_path
        li = link_to 'Statistics', stats_overall_path
        li = link_to 'Rounds', stats_rounds_path
        li = link_to 'Team Settings', edit_myteam_path

      ul.nav.navbar-nav.navbar-right
        li
          = link_to destroy_user_session_path, method: :delete do
            i.fa.fa-sign-out
            = ' Logout'
          end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Lean Elevator Lobby
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'shared/sentry'
    meta name="turbolinks-cache-control" content="no-cache"

    = yield :head
  body

    = render 'layouts/header'

    .container
      - if flash[:notice]
        .alert.alert-info = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger = flash[:alert]
      = yield

app/views/layouts/welcome.html.slim
doctype html
html
  head
    title Lean Elevator Lobby
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      h1 Lean Challenge – Elevators
      - if flash[:notice]
        .alert.alert-info = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger = flash[:alert]
      = yield